version: "3.8"

services:
  n8n:
    # Behalte dein Build, falls dein Dockerfile Playwright installiert.
    # Wenn du kein eigenes Dockerfile nutzt, siehe "Ohne Rebuild" weiter unten.
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-playwright
    #ports:
     # - "5678:5678"
    environment:
      - TZ=Europe/Berlin
      - N8N_ENCRYPTION_KEY=please-set-a-long-random-string

      # Öffentliche URL für OAuth (ngrok-Domain)
      #- N8N_HOST=racemously-noncombat-lacie.ngrok-free.dev
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://192.168.188.65/
      - N8N_EDITOR_BASE=https://192.168.188.65/
      # GROGH Tunnel for OAutuh2.0 Authentification
      - WEBHOOK_TUNNEL_URL=https://racemously-noncombat-lacie.ngrok-free.dev
      - N8N_PORT=5678
      
      # WICHTIG für Code-Node:
      - NODE_FUNCTION_ALLOW_EXTERNAL=playwright
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_PATH=/usr/local/lib/node_modules

      # Enforce Settings to avoid user pemission problems
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      #- n8n_data:/home/n8nuser/.n8n
      - n8n_data:/var/lib/docker/volumes/n8n_data/_data
    restart: unless-stopped
    networks: [nnet]

  caddy:
    image: caddy:2-alpine
    container_name: n8n-caddy
    depends_on: [n8n]
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks: [nnet]

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: n8n-ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=racemously-noncombat-lacie.ngrok-free.dev"
      - "http://n8n:5678"
    restart: unless-stopped
    networks: [nnet]

networks:
  nnet:

volumes:
  n8n_data:
  caddy_data:
  caddy_config:
