version: "3.8"

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-playwright
    environment:
      - TZ=Europe/Berlin
      - N8N_ENCRYPTION_KEY=please-set-a-long-random-string
      
      # Lokaler HTTPS-Zugriff über Caddy
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://192.168.188.65/
      - N8N_EDITOR_BASE_URL=https://192.168.188.65/
      
      # ngrok Tunnel für OAuth2 Callbacks
      - WEBHOOK_TUNNEL_URL=https://racemously-noncombat-lacie.ngrok-free.dev/
      
      - N8N_PORT=5678
      
      # Code-Node Settings
      - NODE_FUNCTION_ALLOW_EXTERNAL=playwright
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_PATH=/usr/local/lib/node_modules
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/home/n8nuser/.n8n
    restart: unless-stopped
    networks:
      - nnet

  caddy:
    image: caddy:2-alpine
    container_name: n8n-caddy
    depends_on:
      - n8n
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - nnet

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: n8n-ngrok
    depends_on:
      - caddy
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=racemously-noncombat-lacie.ngrok-free.dev"
      - "caddy:80"
    restart: unless-stopped
    networks:
      - nnet

networks:
  nnet:
    driver: bridge

volumes:
  n8n_data:
  caddy_data:
  caddy_config: